get_card:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: boardoil
    board_id:
      required: true
      selector:
        number:
          min: 1
          mode: box
    card_id:
      required: true
      selector:
        number:
          min: 1
          mode: box

get_cards:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: boardoil
    board_id:
      required: true
      selector:
        number:
          min: 1
          mode: box
    column_id:
      required: false
      selector:
        number:
          min: 1
          mode: box

add_card:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: boardoil
    board_id:
      required: true
      selector:
        number:
          min: 1
          mode: box
    column_id:
      required: false
      selector:
        number:
          min: 1
          mode: box
    card_type_id:
      required: false
      selector:
        number:
          min: 1
          mode: box
    title:
      required: true
      selector:
        text:
    description:
      required: false
      selector:
        text:
          multiline: true
    tag_names:
      required: false
      selector:
        text:
          multiline: true
    slick_name:
      required: false
      selector:
        text:
    external_url:
      required: false
      selector:
        text:
